version: "3.8"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=26305721 # change this to your ID
       - API_HASH=f7fabb6bb9951b499e66f7c44331011d # change this to your HASH
       - BOT_TOKEN=6437310923:AAGLvbmoZnEwhLkXYYrMcKJWBSMgSjS9CxM #TGFileDownloadBot
       - BIN_CHANNEL=-1002112631258 # paste channel ID
      ports:
       - 127.0.0.1:8000:80
      volumes:
       - $HOME/TG-FileStreamBot:/app/.env
